name: bhargavi example

on:
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: run sample commands of linux
        run: |
          echo chandu and bhargavi
          lsblk
          ps -ef | grep "apache2"
          echo running chandu
  install:
    runs-on: ubuntu-latest

    steps:
      - name: update apt
        run: sudo apt update
      - name: install apache2
        run: sudo apt install apache2
      - name : run rest commands
        run: |
          apache2 -version
          sudo ufw app list
          sudo ufw allow 'Apache'
          sudo systemctl status apache2
          hostname -I
